# -*- coding: utf-8 -*-
"""02.12.20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xtBWQxKYzjtDUGTjQS5V07_Oev2kYmoP
"""

a=int(input())
b=int(input())
c=int(input())
d=int(input())
def min4(a,b,c,d):
  return min(min(min(a,b),c),d)
print("Минимальное число: " , min4(a,b,c,d))

"""Задание 2: наибольший делитель числа"""

n=int(input())
def my_div(n):
  max=n
  for i in range(2,n//2+1):
    if n%i==0:
      max=i
  return max
print("Наибольший делитель числа: " , str(my_div(n)))

"""Задание 3"""

a=int(input())
b=int(input())
def my_sum(a,b):
  if a==0:
    return b
  return my_sum(a-1,b+1)
print("Сумма равна: ", my_sum(a,b))

"""Задание 4

"""

a=int(input())
n=int(input())
def my_power(a,n):
  if n==0:
    return 1
  return a*my_power(a,n-1)
print(str(my_power(a,n)))

"""Задание 5

"""

xx = ['Makar Sidorov 23', 'Maria Kuznetsova 20', 'Reter Petrov 19', 'Ivan Ivanov 21']
print(sorted(xx, key = lambda x: str(x[-2:])))
print(min(xx, key = lambda x:str(x[-2])))