# -*- coding: utf-8 -*-
"""Git1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MtUlouwAXuOD1RKx3lF-yfY8HHpjUvcu
"""

a=int(input())
b=int(input())
if a<b:
  for i in range(1,11):
    print(i)
else:
  for i in range(10,0,-1):
    print(i)