# -*- coding: utf-8 -*-
"""git2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iObhhwLPFrZeh47zZo2xtGCeA5srbE6D
"""

a=int(input())
b=int(input())
for i in range(a,b+1):
  c=str(i)
  d=str(i)[::-1]
  if c==d:
    print(c)